### ISSUE TITLE
Zelda Picross Not Launching

### ISSUE THREAD

**Issue by MichaelRPowell** [OnionUI/Ports-Collection#16]
I am using the Miyoo Mini Plus. I have Onion OS 4.2 beta. A few ports work fine, but Zelda Picross fails to launch. I see it trying to load, then it goes back to the main menu.

I am not clear on exactly what the issue is. I am happy to check logs if there is a place to look to see what went wrong to provide troubleshooting information.

Thank you for all the work putting this collection together!

**Comment by schmurtzm** [comment]
Thank you for the feedback. I have to investigate on this 🤔

**Comment by MichaelRPowell** [comment]
If I can assist in any way, please let me know. Other ports I tested are running flawlessly!

**Comment by MooseyGoosey** [comment]
Same issue for me as well, on the newest Onion Beta

**Comment by schmurtzm** [comment]
Hi, to fix it just add `unset LD_PRELOAD` to `Roms/PORTS/Shortcuts/Puzzle games/Zelda Picross.port`


Zelda Picross.port should look like this (it will updated in next release) : 

```bash
#!/bin/sh
# Standalone Ports Script Template

# main configuration :
GameName="Zelda Picross (Port)"  			# Used for Onion "recents" and "activity tracker"
GameDir="Zelda Picross"  					# Directy name of the port in /mnt/SDCARD/Roms/PORTS/Games
GameExecutable="Zelda-Picross"				# Executable name of the port
GameDataFile=""								# Used to detect if the port is currently installed or not, sometime the main executable is present but not the assets (cf diablo port) 

# additional configuration
KillAudioserver=1
PerformanceMode=0

# specific to this port :
Arguments=""								# Here you can specify some additional command arguments to the port launch command line
unset LD_PRELOAD

# running command line :
/mnt/SDCARD/Emu/PORTS/launch_standalone.sh "$GameName" "$GameDir" "$GameExecutable" "$Arguments" "$GameDataFile" "$KillAudioserver" "$PerformanceMode"

```

**Comment by schmurtzm** [comment]
Fixed in Onion ports v1.0.8 : 
https://github.com/OnionUI/Ports-Collection/commit/57eb5b0d4ce156730aec46abdf251c4a51d99f63
https://github.com/OnionUI/Ports-Collection/commit/9c756e27501f80382db7528b7f0101eba83326ce

**Comment by MichaelRPowell** [comment]
Hello!

Thank you for the work. I downloaded the 1.0.8 update. I deleted the previous version of Zelda Picross and uploaded the new files. I am still getting the "Loading..." followed by being booted back to the Ports menu.

I have checked the `Roms/PORTS/Shortcuts/Puzzle games/Zelda Picross.port` file. I do see `unset LD_PRELOAD`. I believe the only change recommended is in place because of this, but I still have no success running it.

Is there any log file I can provide to help further troubleshoot?
